### ISSUE TITLE
Credentials get logged when Ansible playbook is run in verbose mode

### ISSUE THREAD

**Issue by sitaramkm** [Venafi/ansible-role-venafi#11]
**PROBLEM SUMMARY**
When Ansible playbook is run in verbose mode credentials get logged. 

**STEPS TO REPRODUCE**
Run the Ansible playbook using Venafi Ansible Role.
This is without using Ansible Vault to encrypt credentials.  
`ansible-playbook -vvv sample.yml`

**EXPECTED RESULTS**
The contents of credentials.yml should not be logged.

**ACTUAL RESULTS**
Contents of credentials.yml gets logged

**ENVIRONMENT DETAILS**
Latest venafi Ansible Role from Ansible Galaxy
vcert += 0.6.7 

**COMMENTS/WORKAROUNDS**
Workaround is always use Ansible Vault to encrypt credentials file.

**Comment by arykalin** [comment]
Added no_log to the credentials facts
