### ISSUE TITLE
Errors while running Venafi role from Ansible

### ISSUE THREAD

**Issue by dominick-hbc** [Venafi/ansible-role-venafi#52]
Dear Colleagues, 

We could really use some help debugging issues with using the Venafi role via Ansible. Here is the error we received:

"module_stderr": "ERROR:root:Unknown error format: {'Error': 'Need a certificate authority (CADN)

Here is the full log:

[debuggingIssueswiththeVenafiAnsibleRole_excerpt.docx](https://github.com/Venafi/ansible-role-venafi/files/6889586/debuggingIssueswiththeVenafiAnsibleRole_excerpt.docx)

**Comment by paulternate** [comment]
@dominick-hbc That error message usually means a CA Template needs to be assigned on your target Zone/Policy Folder in Trust Protection Platform. I would suggest checking to see if you have a CA Template assigned on the "Sample Policy" Zone you're targeting.

**Comment by tr1ck3r** [comment]
It was confirmed that was indeed the issue... no CA template had been assigned by policy to the target zone (folder).
