### ISSUE TITLE
Getting error, vcert.yml file is not able to locate the role.

### ISSUE THREAD

**Issue by nhemchandra** [Venafi/ansible-role-venafi#7]
$ cat vcert.yml 
- hosts: localhost
  roles:
    - role: venafi.ansible_role_venafi
      certificate_cert_dir: "/tmp/etc/ssl/{{ certificate_common_name }}"

$ ansible-playbook vcert.yml
ERROR! the role 'venafi.ansible_role_venafi' was not found in /apps/Ansible/ansible-role-venafi-master/roles:/apps/Ansible:/apps/Ansible/tests/roles:/apps/Ansible/ansible-role-venafi-master

The error appears to have been in '/apps/Ansible/ansible-role-venafi-master/vcert.yml': line 3, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: venafi.ansible_role_venafi
      ^ here

**Comment by arykalin** [comment]
Hi @nhemchandra how you installed the role? Did you clone it from here or install it via ansible galaxy?

**Comment by nhemchandra** [comment]
I Cloned or from git

**Comment by tr1ck3r** [comment]
@nhemchandra were you able to resolve your issue?

**Comment by nhemchandra** [comment]
No sir, I give up.

I'm happy if you can help and I can give a shot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tr1ck3r** [comment]
@nhemchandra please try running `pip install vcert --upgrade` and `ansible-galaxy install venafi.ansible_role_venafi`, and then re-run `ansible-playbook vcert.yml`.
